{"uuid":"030ff209-049f-468a-bcd3-d211563c192c","historyId":"867c03470c50eb92f74663a1c6901ca8","fullName":"Tests.RegisterTest.testValidRegister","labels":[{"name":"package","value":"Tests.RegisterTest"},{"name":"testClass","value":"Tests.RegisterTest"},{"name":"testMethod","value":"testValidRegister"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"OrangeTask"},{"name":"subSuite","value":"Tests.RegisterTest"},{"name":"host","value":"DESKTOP-UL4KEHA"},{"name":"thread","value":"12812@DESKTOP-UL4KEHA.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Valid Register Test"},{"name":"feature","value":"Register User"},{"name":"epic","value":"User Registration"}],"links":[],"name":"testValidRegister","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"login wasn't successful and this is failure test case expected [false] but found [true]","trace":"java.lang.AssertionError: login wasn't successful and this is failure test case expected [false] but found [true]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertFalse(Assert.java:79)\r\n\tat Pages.RegisterPage.performRegister(RegisterPage.java:95)\r\n\tat Tests.RegisterTest.testValidRegister(RegisterTest.java:28)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Verify that a user can register successfully with valid data","steps":[],"attachments":[],"parameters":[],"start":1728158130799,"stop":1728158162256}